In [2]:
import numpy as np
import math
from sympy import Matrix, linsolve, symbols

In [3]:
def mu(i):
    return i % 2
def nu(i):
    return (i // 2) % 2
def th(i):
    return (i // 4)

In [4]:
G = np.array(
    [[1,-1],
     [-1, 1]])
M = np.array(
    [[2, 1],
     [1, 2]])

GMM = np.zeros((8,8))
MGM = np.zeros((8,8))
MMG = np.zeros((8,8))
MMM = np.zeros((8,8))

for i in range(8):
    for j in range(8):
        GMM[i][j] = G[mu(i)][mu(j)] * M[nu(i)][nu(j)] * M[th(i)][th(j)]
        MGM[i][j] = M[mu(i)][mu(j)] * G[nu(i)][nu(j)] * M[th(i)][th(j)]
        MMG[i][j] = M[mu(i)][mu(j)] * M[nu(i)][nu(j)] * G[th(i)][th(j)]
        MMM[i][j] = M[mu(i)][mu(j)] * M[nu(i)][nu(j)] * M[th(i)][th(j)]

In [5]:
def out(file_name, mat):
    with open(file_name, "w") as f:
    	for i in range(8):
    	    f.write(str(mat[i][i]))
    	    f.write(" ")
    	f.write("\n")
    	for i in range(8):
            for j in range(i):
                f.write(str(mat[i][j]))
                f.write(" ")

In [6]:
out("data/GMM.txt", GMM)
out("data/MGM.txt", MGM)
out("data/MMG.txt", MMG)
out("data/MMM.txt", MMM)

In [8]:
print(MMM)

[[8. 4. 4. 2. 4. 2. 2. 1.]
 [4. 8. 2. 4. 2. 4. 1. 2.]
 [4. 2. 8. 4. 2. 1. 4. 2.]
 [2. 4. 4. 8. 1. 2. 2. 4.]
 [4. 2. 2. 1. 8. 4. 4. 2.]
 [2. 4. 1. 2. 4. 8. 2. 4.]
 [2. 1. 4. 2. 4. 2. 8. 4.]
 [1. 2. 2. 4. 2. 4. 4. 8.]]
